---
title: "Evolution plots"
author: "John Wilshire"
date: "18 February 2016"
output:
  pdf_document: default
  html_document: default
---

```{r, echo=FALSE}
library(jsonlite)
library(plyr)
library(ggplot2)
source("~/Documents/contests_model/R/load_datasets.R")
source("~/Documents/contests_model/R/make_plots.R")
```

These are roughly equivilant to the density plots but I feel the density plot is a little bit too messy...


```{R,, echo=FALSE}

exp_100 <- load_population("~/Documents/contests_model/data/cm_100/")
# linf10_pop <- load_population("../data/lin_f10/")
# exp10_1000_pop <- load_population("../data/exp_f10_1000/")
population_plots <- function (y, x, title=""){
    print(pop_values(exp_100, x, y, paste(title,"exp_100", y)))
}

population_plots("e_0", "patch_area")
population_plots("k", "patch_area")

```

These plots are against the log of the nest density ie log(nests / patch_area)

```{R, , echo=FALSE}
population_plots("e_0", "log(N / patch_area)","density -> ")
population_plots("k", "log(N / patch_area)", "density -> ")

```

now the energy plot

```{R, echo=FALSE}
exp_trait_100 <- load_trait_history("~/Documents/contests_model/data/cm_100/")
last <- get_generation(exp_trait_100,499)
energy_pc_plot(last, "patch_area")

```

This is the with the nest density increasing $\rightarrow$


```{R,, echo=FALSE}

energy_pc_plot(last, "log( 500 / patch_area )")

```


```{r, echo=FALSE}
# exp_100_trait <- load_trait_history("~/Documents/contests_model/data/cm_100/")
# 
# evolution_plots <- function (what){
#   print(trait_evolution_plot(exp_100_trait, what, paste("exp_100", what)))
# }
# 
# evolution_plots("mean_k")
# evolution_plots("std_k")
# evolution_plots("std_e_0")
# evolution_plots("num_winners")
# evolution_plots("mean_maturation")
# evolution_plots("contest_energy")
# evolution_plots("search_energy")
# evolution_plots("occupying_energy")
# evolution_plots("mean_exploration")
# evolution_plots("std_exploration")
```